Parse relationship from url with trailing slashes
miLibris/flask-rest-jsonapi pull request #144
Opened 2019-03-11 18:57 UTC by vladmunteanu

After issuing a request to an endpoint like /<resource_a>/<id>/relationships/<resource_b>/ , the resource_b field is not identified as a relationship.
I'm pretty sure the following line is causing the issue: https://github.com/miLibris/flask-rest-jsonapi/blob/ad3f90f81955fa41aaf0fb8c49a75a5fbe334f5f/flask_rest_jsonapi/resource.py#L506

This is because the last item of request.path.split('/') is actually an empty string:
```
>>> s = '/api/users/5/relationships/organization/'
>>> s.split('/')
['', 'api', 'users', '5', 'relationships', 'organization', '']
>>> s = '/api/users/5/relationships/organization'
>>> s.split('/')
['', 'api', 'users', '5', 'relationships', 'organization']
```

2019-03-13 08:36 UTC, vladmunteanu commented
You can view a minimal example here: https://github.com/vladmunteanu/apiex-flask-rest-jsonapi
For this project, the relationship management will not work because of this issue.

2020-09-29 08:30 UTC, akira-dev requested changes

2020-09-29 08:30 UTC, akira-dev commented on flask_rest_jsonapi/resource.py
> +        relationship_field = url.split('/')[-1].replace('-', '_')
I think it is not good because you split on a list so it doesn't works ?

2020-09-29 09:14 UTC, closed without merging

2020-09-29 09:14 UTC, vladmunteanu commented
Thanks for checking this @akira-dev, but honestly i wasn't right to begin with. That kind of URL should not have a leading slash.